version: '2'

services:
  dashboard:
    build:
      context: AutoDetailsShopFront/.
    ports:
      - "4200:4200"
    container_name: front
      
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: AutoDetailsShopBack/.
    ports:
      - "8080:8080"
    container_name: back
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/max
      - SPRING_DATASOURCE_USERNAME=max
      - SPRING_DATASOURCE_PASSWORD=max
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVAX_PERSISTENCE_JDBC_URL=jdbc:postgresql://db:5432/max
      - JAVAX_PERSISTENCE_JDBC_USER=max
      - JAVAX_PERSISTENCE_JDBC_PASSWORD=max
      - HIBERNATE_HBM2DDL_AUTO=update
      - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL9Dialect
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=max
      - POSTGRES_PASSWORD=max
    volumes:
      - .:/docker-entrypoint-initdb.d